import type { Summary } from "../types.js";

export function toMarkdown(summary: Summary): string {
  const { components, licenses, risk } = summary;

  const riskEmoji =
    risk.red > 0 ? "🔴" : risk.yellow > 0 ? "🟡" : "🟢";

  return `
# ${riskEmoji} ClearBOM Security Report

| Metric | Count | Status |
| :--- | :--- | :--- |
| **Total Components** | **${components}** | ℹ️ |
| 🟢 **Low Risk** | ${risk.green} | Permissive |
| 🟡 **Medium Risk** | ${risk.yellow} | Review Needed |
| 🔴 **High Risk** | ${risk.red} | **Restricted** |

## 📜 License Breakdown
- **Permissive:** ${licenses.permissive}
- **Copyleft:** ${licenses.copyleft}
- **Proprietary:** ${licenses.proprietary}
- **Unknown:** ${licenses.unknown}

${
  summary.violations && summary.violations.length > 0
    ? `
## ❌ Policy Violations
| Component | Severity | Reason |
| :--- | :--- | :--- |
${summary.violations
  .map(
    (v) =>
      `| \`${v.component}\` | ${
        v.severity === "error" ? "🔴 Critical" : "🟡 Warning"
      } | ${v.reason} |`
  )
  .join("\n")}
`
    : "\n✅ **No Policy Violations Found**"
}

---
*Generated by [ClearBOM](https://github.com/ennachite/clearbom)*
`;
}
